spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8888
  gateway:
    routes:
      - id: myService
        uri: http://localhost:8081
        predicates:
          - Path=/my-service/**

server:
  port: 8082