server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
      - id: myService
        uri: http://localhost:8081
        predicates:
        - Path=/my-service/**

